#!/usr/bin/env python3
"""
Keyword screening script for AI Policy (AIP) identification.
Scans downloaded CONTRIBUTING.md files using a two-layer keyword matching approach.
Layer 1 detects AI content references; Layer 2 captures policy stances.
A repository is flagged as a candidate only when at least one pattern from each layer matches.
"""

import os
import re
import csv
import argparse
from collections import defaultdict, Counter

# Layer 1: AI-Content Keywords (40 patterns)
L1_PATTERNS = [
    (r'\bai[- ]?generated\b', 'ai-generated'),
    (r'\bai[- ]?assisted\b', 'ai-assisted'),
    (r'\bai[- ]?assistance\b', 'ai-assistance'),
    (r'\bgenerated by ai\b', 'generated by ai'),
    (r'\bai output\b', 'ai output'),
    (r'\bai produced\b', 'ai produced'),
    (r'\bai written\b', 'ai written'),
    (r'\bai code\b', 'ai code'),
    (r'\bai tool\b', 'ai tool'),
    (r'\bai tools\b', 'ai tools'),
    (r'\bai[- ]?created\b', 'ai-created'),
    (r'\bai[- ]?authored\b', 'ai-authored'),
    (r'\bai[- ]?drafted\b', 'ai-drafted'),
    (r'\bai[- ]?suggested\b', 'ai-suggested'),
    (r'\bai[- ]?reviewed\b', 'ai-reviewed'),
    (r'\bgenerated by (?:chatgpt|copilot|claude|gemini|gpt|llm|openai)\b', 'generated by [tool]'),
    (r'\bwritten by (?:ai|chatgpt|copilot|claude|gemini|gpt|llm)\b', 'written by [tool]'),
    (r'\bcode generated by\b', 'code generated by'),
    (r'\bcode written by\b', 'code written by'),
    (r'\bsubmitted by ai\b', 'submitted by ai'),
    (r'\bcontributed by ai\b', 'contributed by ai'),
    (r'\bai (?:wrote|created|generated|produced|drafted)\b', 'ai [verb]'),
    (r'\b(?:wrote|created|generated|produced|drafted) (?:by|with|using) ai\b', '[verb] by/with/using ai'),
    (r'\bai pair programming\b', 'ai pair programming'),
    (r'\bai coding assistant\b', 'ai coding assistant'),
    (r'\bai coding aid\b', 'ai coding aid'),
    (r'\bai development aid\b', 'ai development aid'),
    (r'\bai[- ]?powered\b', 'ai-powered'),
    (r'\bai[- ]?driven\b', 'ai-driven'),
    (r'\bllm[- ]?generated\b', 'llm-generated'),
    (r'\bllm[- ]?assisted\b', 'llm-assisted'),
    (r'\bllm[- ]?produced\b', 'llm-produced'),
    (r'\bllm[- ]?written\b', 'llm-written'),
    (r'\bllm output\b', 'llm output'),
    (r'\bllm code\b', 'llm code'),
    (r'\bai[- ]?generated (?:pr|pull request|commit|patch|code|content)\b', 'ai-generated [object]'),
    (r'\b(?:massive|large|giant|bulk) ai[- ]?generated\b', 'massive ai-generated'),
    (r'\bautomated pr\b', 'automated pr'),
    (r'\bautomated contribution\b', 'automated contribution'),
    (r'\bco[- ]?authored (?:by |with )(?:ai|chatgpt|copilot|claude|gemini|gpt|llm)\b', 'co-authored with [tool]'),
]

# Layer 2: AI-Policy Keywords (48 patterns)
L2_PATTERNS = [
    (r'\bai policy\b', 'ai policy'),
    (r'\bai contribution\b', 'ai contribution'),
    (r'\bai use\b', 'ai use'),
    (r'\busing ai\b', 'using ai'),
    (r'\buse of ai\b', 'use of ai'),
    (r'\bai disclosure\b', 'ai disclosure'),
    (r'\bdisclose ai\b', 'disclose ai'),
    (r'\bai transparency\b', 'ai transparency'),
    (r'\bai guidelines\b', 'ai guidelines'),
    (r'\bai rules\b', 'ai rules'),
    (r'\bpolicy on ai\b', 'policy on ai'),
    (r'\bpolicies.*\bai\b', 'policies...ai'),
    (r'\bai.*\bpolicy\b', 'ai...policy'),
    (r'\bai (?:is |are )?(?:not )?(?:allowed|permitted|welcome|accepted|prohibited|forbidden|banned|discouraged|encouraged|supported)\b', 'ai [not] [stance]'),
    (r'\b(?:allow|permit|welcome|accept|prohibit|forbid|ban|discourage|encourage|support).*\bai\b', '[stance_verb]...ai'),
    (r'\bno ai\b', 'no ai'),
    (r'\bai[- ]?free\b', 'ai-free'),
    (r'\bdisclose.*(?:ai|artificial)\b', 'disclose...ai'),
    (r'\b(?:ai|artificial).*disclose\b', 'ai...disclose'),
    (r'\bmark.*\bai[- ]?generated\b', 'mark ai-generated'),
    (r'\blabel.*\bai[- ]?generated\b', 'label ai-generated'),
    (r'\btag.*\bai[- ]?generated\b', 'tag ai-generated'),
    (r'\bflag.*\bai[- ]?generated\b', 'flag ai-generated'),
    (r'\b(?:ai|artificial).*(?:attribution|credit|acknowledge)\b', 'ai...attribution'),
    (r'\b(?:attribution|credit|acknowledge).*\bai\b', 'attribution...ai'),
    (r'\bresponsible for ai\b', 'responsible for ai'),
    (r'\bai.*\bresponsib\b', 'ai...responsible'),
    (r'\bresponsib.*\bai\b', 'responsible...ai'),
    (r'\bai.*\baccountab\b', 'ai...accountable'),
    (r'\baccountab.*\bai\b', 'accountable...ai'),
    (r'\bhuman.*\breview.*\bai\b', 'human...review...ai'),
    (r'\bai.*\breview.*\bhuman\b', 'ai...review...human'),
    (r'\bunderstand.*\bai[- ]?generated\b', 'understand ai-generated'),
    (r'\bai[- ]?generated.*\bunderstand\b', 'ai-generated...understand'),
    (r'\bai[- ]?assisted (?:contribution|development|coding|work)\b', 'ai-assisted [activity]'),
    (r'\bai[- ]?assistance (?:policy|guideline|rule|statement)\b', 'ai-assistance [policy_type]'),
    (r'\b(?:contribution|contributing).*\bai\b', 'contribution...ai'),
    (r'\bhuman (?:oversight|review|approval|verification)\b.*\bai\b', 'human [oversight]...ai'),
    (r'\bai\b.*\bhuman (?:oversight|review|approval|verification)\b', 'ai...human [oversight]'),
    (r'\breview.*\bai[- ]?generated\b', 'review ai-generated'),
    (r'\bai (?:declaration|statement|disclaimer|notice)\b', 'ai [declaration_type]'),
    (r'\bdeclaration.*\bai\b', 'declaration...ai'),
    (r'\bstatement.*\bai\b', 'statement...ai'),
    (r'\bstance on ai\b', 'stance on ai'),
    (r'\bposition on ai\b', 'position on ai'),
    (r'\bapproach to ai\b', 'approach to ai'),
    (r'\bartificial intelligence.*(?:policy|guideline|rule|statement)\b', 'artificial intelligence...policy'),
    (r'\b(?:policy|guideline|rule|statement).*artificial intelligence\b', 'policy...artificial intelligence'),
]


def extract_context(content, match_obj, window=200):
    start = max(0, match_obj.start() - window)
    end = min(len(content), match_obj.end() + window)
    ctx = content[start:end].replace('\n', ' ').strip()
    return ctx


def scan_files(dl_dir, sample=None):
    files = sorted(os.listdir(dl_dir))
    if sample:
        import random
        random.seed(42)
        files = random.sample(files, min(sample, len(files)))

    results = {}
    layer_files = defaultdict(set)
    layer_kw_counts = Counter()

    for fname in files:
        fpath = os.path.join(dl_dir, fname)
        with open(fpath, 'r', encoding='utf-8', errors='ignore') as f:
            content = f.read()
        content_lower = content.lower()

        for patterns, layer in [(L1_PATTERNS, 'L1'), (L2_PATTERNS, 'L2')]:
            for pat, label in patterns:
                m = re.search(pat, content_lower)
                if m:
                    if fname not in results:
                        results[fname] = {'L1': [], 'L2': []}
                    ctx = extract_context(content, m)
                    results[fname][layer].append((label, m.group(), ctx))
                    layer_files[layer].add(fname)
                    layer_kw_counts[f'{layer}:{label}'] += 1

    return results, layer_files, layer_kw_counts


def print_stats(results, layer_files, layer_kw_counts, total_files):
    any_hit = set()
    for s in layer_files.values():
        any_hit.update(s)

    print("=== AIP Two-Layer Keyword Screening Results ===")
    print(f"Total files scanned: {total_files}")
    print(f"L1 hits: {len(layer_files['L1'])} ({len(layer_files['L1'])/total_files*100:.2f}%)")
    print(f"L2 hits: {len(layer_files['L2'])} ({len(layer_files['L2'])/total_files*100:.2f}%)")
    print(f"L1 or L2: {len(any_hit)} ({len(any_hit)/total_files*100:.2f}%)")
    print(f"L1 and L2 (candidates): {len(layer_files['L1'] & layer_files['L2'])}")

    print("\n--- L1 Keyword Hits (Top 20) ---")
    l1_items = [(k.replace('L1:',''), v) for k, v in layer_kw_counts.items() if k.startswith('L1:')]
    for kw, cnt in sorted(l1_items, key=lambda x: -x[1])[:20]:
        print(f"  {kw}: {cnt}")

    print("\n--- L2 Keyword Hits (Top 20) ---")
    l2_items = [(k.replace('L2:',''), v) for k, v in layer_kw_counts.items() if k.startswith('L2:')]
    for kw, cnt in sorted(l2_items, key=lambda x: -x[1])[:20]:
        print(f"  {kw}: {cnt}")


def export_csv(results, output_path):
    with open(output_path, 'w', newline='', encoding='utf-8') as f:
        writer = csv.writer(f)
        writer.writerow(['filename', 'repo_name', 'L1_hit', 'L2_hit', 'L1_keywords', 'L2_keywords', 'L1_context', 'L2_context'])
        for fname, info in sorted(results.items()):
            repo = fname.replace('_root_contributing.md','').replace('_docs_contributing.md','').replace('_.github_contributing.md','')
            repo = repo.replace('_', '/', 1)
            l1_kws = '; '.join(set(label for label, _, _ in info['L1']))
            l2_kws = '; '.join(set(label for label, _, _ in info['L2']))
            l1_ctx = ' | '.join(ctx for _, _, ctx in info['L1'][:3])
            l2_ctx = ' | '.join(ctx for _, _, ctx in info['L2'][:3])
            writer.writerow([fname, repo, bool(info['L1']), bool(info['L2']), l1_kws, l2_kws, l1_ctx, l2_ctx])
    print(f"Exported: {output_path} ({len(results)} records)")


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='AIP two-layer keyword screening')
    parser.add_argument('--sample', type=int, help='Random sample size (default: scan all)')
    parser.add_argument('--export', action='store_true', help='Export CSV results')
    parser.add_argument('--dl-dir', required=True, help='Directory containing downloaded CONTRIBUTING.md files')
    parser.add_argument('--output', default='screening_results.csv', help='Output CSV path')
    args = parser.parse_args()

    results, layer_files, layer_kw_counts = scan_files(args.dl_dir, args.sample)
    total = len(os.listdir(args.dl_dir))
    print_stats(results, layer_files, layer_kw_counts, total)

    if args.export:
        export_csv(results, args.output)