#!/usr/bin/env python3
"""
Keyword screening script for AI Policy (AIP) identification.
Scans downloaded CONTRIBUTING.md files using a two-layer keyword matching approach.
Layer 1 detects AI content references; Layer 2 captures policy stances.
A repository is flagged as a candidate when any of its guideline files matches
at least one pattern from either layer.
"""

import os
import re
import csv
import argparse
from collections import defaultdict, Counter

# Layer 1: AI-Content Keywords (40 patterns)
L1_PATTERNS = [
    (r'\bai[- ]?generated\b', 'ai-generated'),
    (r'\bai[- ]?assisted\b', 'ai-assisted'),
    (r'\bai[- ]?assistance\b', 'ai-assistance'),
    (r'\bgenerated by ai\b', 'generated by ai'),
    (r'\bai output\b', 'ai output'),
    (r'\bai produced\b', 'ai produced'),
    (r'\bai written\b', 'ai written'),
    (r'\bai code\b', 'ai code'),
    (r'\bai tool\b', 'ai tool'),
    (r'\bai tools\b', 'ai tools'),
    (r'\bai[- ]?created\b', 'ai-created'),
    (r'\bai[- ]?authored\b', 'ai-authored'),
    (r'\bai[- ]?drafted\b', 'ai-drafted'),
    (r'\bai[- ]?suggested\b', 'ai-suggested'),
    (r'\bai[- ]?reviewed\b', 'ai-reviewed'),
    (r'\bgenerated by (?:chatgpt|copilot|claude|gemini|gpt|llm|openai)\b', 'generated by [tool]'),
    (r'\bwritten by (?:ai|chatgpt|copilot|claude|gemini|gpt|llm)\b', 'written by [tool]'),
    (r'\bcode generated by\b', 'code generated by'),
    (r'\bcode written by\b', 'code written by'),
    (r'\bsubmitted by ai\b', 'submitted by ai'),
    (r'\bcontributed by ai\b', 'contributed by ai'),
    (r'\bai (?:wrote|created|generated|produced|drafted)\b', 'ai [verb]'),
    (r'\b(?:wrote|created|generated|produced|drafted) (?:by|with|using) ai\b', '[verb] by/with/using ai'),
    (r'\bai pair programming\b', 'ai pair programming'),
    (r'\bai coding assistant\b', 'ai coding assistant'),
    (r'\bai coding aid\b', 'ai coding aid'),
    (r'\bai development aid\b', 'ai development aid'),
    (r'\bai[- ]?powered\b', 'ai-powered'),
    (r'\bai[- ]?driven\b', 'ai-driven'),
    (r'\bllm[- ]?generated\b', 'llm-generated'),
    (r'\bllm[- ]?assisted\b', 'llm-assisted'),
    (r'\bllm[- ]?produced\b', 'llm-produced'),
    (r'\bllm[- ]?written\b', 'llm-written'),
    (r'\bllm output\b', 'llm output'),
    (r'\bllm code\b', 'llm code'),
    (r'\bai[- ]?generated (?:pr|pull request|commit|patch|code|content)\b', 'ai-generated [object]'),
    (r'\b(?:massive|large|giant|bulk) ai[- ]?generated\b', 'massive ai-generated'),
    (r'\bautomated pr\b', 'automated pr'),
    (r'\bautomated contribution\b', 'automated contribution'),
    (r'\bco[- ]?authored (?:by |with )(?:ai|chatgpt|copilot|claude|gemini|gpt|llm)\b', 'co-authored with [tool]'),
]

# Layer 2: AI-Policy Keywords (48 patterns)
L2_PATTERNS = [
    (r'\bai policy\b', 'ai policy'),
    (r'\bai contribution\b', 'ai contribution'),
    (r'\bai use\b', 'ai use'),
    (r'\busing ai\b', 'using ai'),
    (r'\buse of ai\b', 'use of ai'),
    (r'\bai disclosure\b', 'ai disclosure'),
    (r'\bdisclose ai\b', 'disclose ai'),
    (r'\bai transparency\b', 'ai transparency'),
    (r'\bai guidelines\b', 'ai guidelines'),
    (r'\bai rules\b', 'ai rules'),
    (r'\bpolicy on ai\b', 'policy on ai'),
    (r'\bpolicies.*\bai\b', 'policies...ai'),
    (r'\bai.*\bpolicy\b', 'ai...policy'),
    (r'\bai (?:is |are )?(?:not )?(?:allowed|permitted|welcome|accepted|prohibited|forbidden|banned|discouraged|encouraged|supported)\b', 'ai [not] [stance]'),
    (r'\b(?:allow|permit|welcome|accept|prohibit|forbid|ban|discourage|encourage|support).*\bai\b', '[stance_verb]...ai'),
    (r'\bno ai\b', 'no ai'),
    (r'\bai[- ]?free\b', 'ai-free'),
    (r'\bdisclose.*(?:ai|artificial)\b', 'disclose...ai'),
    (r'\b(?:ai|artificial).*disclose\b', 'ai...disclose'),
    (r'\bmark.*\bai[- ]?generated\b', 'mark ai-generated'),
    (r'\blabel.*\bai[- ]?generated\b', 'label ai-generated'),
    (r'\btag.*\bai[- ]?generated\b', 'tag ai-generated'),
    (r'\bflag.*\bai[- ]?generated\b', 'flag ai-generated'),
    (r'\b(?:ai|artificial).*(?:attribution|credit|acknowledge)\b', 'ai...attribution'),
    (r'\b(?:attribution|credit|acknowledge).*\bai\b', 'attribution...ai'),
    (r'\bresponsible for ai\b', 'responsible for ai'),
    (r'\bai.*\bresponsib\b', 'ai...responsible'),
    (r'\bresponsib.*\bai\b', 'responsible...ai'),
    (r'\bai.*\baccountab\b', 'ai...accountable'),
    (r'\baccountab.*\bai\b', 'accountable...ai'),
    (r'\bhuman.*\breview.*\bai\b', 'human...review...ai'),
    (r'\bai.*\breview.*\bhuman\b', 'ai...review...human'),
    (r'\bunderstand.*\bai[- ]?generated\b', 'understand ai-generated'),
    (r'\bai[- ]?generated.*\bunderstand\b', 'ai-generated...understand'),
    (r'\bai[- ]?assisted (?:contribution|development|coding|work)\b', 'ai-assisted [activity]'),
    (r'\bai[- ]?assistance (?:policy|guideline|rule|statement)\b', 'ai-assistance [policy_type]'),
    (r'\b(?:contribution|contributing).*\bai\b', 'contribution...ai'),
    (r'\bhuman (?:oversight|review|approval|verification)\b.*\bai\b', 'human [oversight]...ai'),
    (r'\bai\b.*\bhuman (?:oversight|review|approval|verification)\b', 'ai...human [oversight]'),
    (r'\breview.*\bai[- ]?generated\b', 'review ai-generated'),
    (r'\bai (?:declaration|statement|disclaimer|notice)\b', 'ai [declaration_type]'),
    (r'\bdeclaration.*\bai\b', 'declaration...ai'),
    (r'\bstatement.*\bai\b', 'statement...ai'),
    (r'\bstance on ai\b', 'stance on ai'),
    (r'\bposition on ai\b', 'position on ai'),
    (r'\bapproach to ai\b', 'approach to ai'),
    (r'\bartificial intelligence.*(?:policy|guideline|rule|statement)\b', 'artificial intelligence...policy'),
    (r'\b(?:policy|guideline|rule|statement).*artificial intelligence\b', 'policy...artificial intelligence'),
]

PATH_SUFFIXES = ['_.github', '_github', '_root', '_docs']


def repo_of_filename(fname):
    """Map a downloaded filename ({owner}_{repo}[{path}]_contributing.md) to owner/repo."""
    base = fname[:-len('_contributing.md')]
    for suf in PATH_SUFFIXES:
        if base.endswith(suf):
            base = base[:-len(suf)]
            break
    if '_' not in base:
        return base
    owner, repo = base.split('_', 1)
    return f'{owner}/{repo}'


def scan_files(dl_dir):
    files = sorted(f for f in os.listdir(dl_dir) if f.endswith('_contributing.md'))
    repo_l1 = defaultdict(set)   # repo -> set of matched L1 labels
    repo_l2 = defaultdict(set)   # repo -> set of matched L2 labels
    file_l1 = file_l2 = 0

    for fname in files:
        fpath = os.path.join(dl_dir, fname)
        with open(fpath, 'r', encoding='utf-8', errors='ignore') as f:
            content = f.read()
        content_lower = content.lower()
        repo = repo_of_filename(fname)

        hit1 = hit2 = False
        for pat, label in L1_PATTERNS:
            if re.search(pat, content_lower):
                repo_l1[repo].add(label)
                hit1 = True
        for pat, label in L2_PATTERNS:
            if re.search(pat, content_lower):
                repo_l2[repo].add(label)
                hit2 = True
        if hit1:
            file_l1 += 1
        if hit2:
            file_l2 += 1

    # A repository is a candidate when any of its guideline files matches
    # at least one pattern from either layer.
    candidates = {repo for repo in set(repo_l1) | set(repo_l2)}
    total_repos = len({repo_of_filename(f) for f in files})
    return files, file_l1, file_l2, repo_l1, repo_l2, candidates, total_repos


def print_stats(files, file_l1, file_l2, repo_l1, repo_l2, candidates, total_repos):
    print("=== AIP Two-Layer Keyword Screening Results ===")
    print(f"Total files scanned: {len(files)}")
    print(f"Repositories with guideline files: {total_repos}")
    print(f"L1 hits (files): {file_l1}")
    print(f"L2 hits (files): {file_l2}")
    print(f"Candidate repositories (L1 or L2): {len(candidates)}")


def export_candidates(candidates, output_path):
    with open(output_path, 'w', newline='', encoding='utf-8') as f:
        writer = csv.writer(f)
        writer.writerow(['repo_name'])
        for repo in sorted(candidates):
            writer.writerow([repo])
    print(f"Exported candidate repositories: {output_path} ({len(candidates)} records)")


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='AIP two-layer keyword screening')
    parser.add_argument('--dl-dir', required=True, help='Directory containing downloaded CONTRIBUTING.md files')
    parser.add_argument('--export', action='store_true', help='Export the candidate repository list as CSV')
    parser.add_argument('--output', default='screening_results.csv', help='Output CSV path')
    args = parser.parse_args()

    files, file_l1, file_l2, repo_l1, repo_l2, candidates, total_repos = scan_files(args.dl_dir)
    print_stats(files, file_l1, file_l2, repo_l1, repo_l2, candidates, total_repos)
    if args.export:
        export_candidates(candidates, args.output)
