#!/usr/bin/env python3
"""
Re-detect AIP first appearance date using keyword patterns:
- L2 (40 AI-content patterns): AI-generated, AI-assisted, etc.
- L3 (48 AI-policy patterns): AI policy, AI allowed, etc.

A commit is considered to contain AIP if it matches AT LEAST ONE L2 pattern
AND AT LEAST ONE L3 pattern simultaneously.

For each repo, scan contributing_md_history chronologically and record the
first commit date where both L2 and L3 patterns are found.
"""

import os
import re
import pymysql
import pandas as pd
from pathlib import Path
from datetime import datetime

DB_HOST = os.environ.get("DB_HOST", "localhost")
DB_PORT = 3306
DB_USER = os.environ.get("DB_USER", "root")
DB_PASS = os.environ.get("DB_PASS", "")
DB_NAME = os.environ.get("DB_NAME", "ai-policy")
DATA_DIR = Path("data/contributing_files")

# ─── L2: AI Content Patterns (40) ───
L2_PATTERNS = [
    (r'\bai[- ]?generated\b', 'ai-generated'),
    (r'\bai[- ]?assisted\b', 'ai-assisted'),
    (r'\bai[- ]?assistance\b', 'ai-assistance'),
    (r'\bgenerated by ai\b', 'generated by ai'),
    (r'\bai output\b', 'ai output'),
    (r'\bai produced\b', 'ai produced'),
    (r'\bai written\b', 'ai written'),
    (r'\bai code\b', 'ai code'),
    (r'\bai tool\b', 'ai tool'),
    (r'\bai tools\b', 'ai tools'),
    (r'\bai[- ]?created\b', 'ai-created'),
    (r'\bai[- ]?authored\b', 'ai-authored'),
    (r'\bai[- ]?drafted\b', 'ai-drafted'),
    (r'\bai[- ]?suggested\b', 'ai-suggested'),
    (r'\bai[- ]?reviewed\b', 'ai-reviewed'),
    (r'\bgenerated by (?:chatgpt|copilot|claude|gemini|gpt|llm|openai)\b', 'generated by [tool]'),
    (r'\bwritten by (?:ai|chatgpt|copilot|claude|gemini|gpt|llm)\b', 'written by [tool]'),
    (r'\bcode generated by\b', 'code generated by'),
    (r'\bcode written by\b', 'code written by'),
    (r'\bsubmitted by ai\b', 'submitted by ai'),
    (r'\bcontributed by ai\b', 'contributed by ai'),
    (r'\bai (?:wrote|created|generated|produced|drafted)\b', 'ai [verb]'),
    (r'\b(?:wrote|created|generated|produced|drafted) (?:by|with|using) ai\b', '[verb] by/with/using ai'),
    (r'\bai pair programming\b', 'ai pair programming'),
    (r'\bai coding assistant\b', 'ai coding assistant'),
    (r'\bai coding aid\b', 'ai coding aid'),
    (r'\bai development aid\b', 'ai development aid'),
    (r'\bai[- ]?powered\b', 'ai-powered'),
    (r'\bai[- ]?driven\b', 'ai-driven'),
    (r'\bllm[- ]?generated\b', 'llm-generated'),
    (r'\bllm[- ]?assisted\b', 'llm-assisted'),
    (r'\bllm[- ]?produced\b', 'llm-produced'),
    (r'\bllm[- ]?written\b', 'llm-written'),
    (r'\bllm output\b', 'llm output'),
    (r'\bllm code\b', 'llm code'),
    (r'\bai[- ]?generated (?:pr|pull request|commit|patch|code|content)\b', 'ai-generated [object]'),
    (r'\b(?:massive|large|giant|bulk) ai[- ]?generated\b', 'massive ai-generated'),
    (r'\bautomated pr\b', 'automated pr'),
    (r'\bautomated contribution\b', 'automated contribution'),
    # Additional L2 patterns (noun/reference forms)
    (r'\bllms?\b', 'LLM(s)'),
    (r'\bchatgpt\b', 'ChatGPT'),
    (r'\bcopilot\b', 'Copilot'),
    (r'\bclaude\b', 'Claude'),
    (r'\bgpt[- ]?[0-9]*\b', 'GPT'),
    (r'\bgemini\b', 'Gemini'),
    (r'\bopenai\b', 'OpenAI'),
    (r'\bartificial intelligence\b', 'artificial intelligence'),
    (r'\bgenerative ai\b', 'generative AI'),
    (r'\bmachine learning\b', 'machine learning'),
    (r'\blarge language model\b', 'large language model'),
    (r'\bco[- ]?authored (?:by |with )(?:ai|chatgpt|copilot|claude|gemini|gpt|llm)\b', 'co-authored with [tool]'),
]

# ─── L3: AI Policy Patterns (48) ───
L3_PATTERNS = [
    (r'\bai policy\b', 'ai policy'),
    (r'\bai contribution\b', 'ai contribution'),
    (r'\bai use\b', 'ai use'),
    (r'\busing ai\b', 'using ai'),
    (r'\buse of ai\b', 'use of ai'),
    (r'\bai disclosure\b', 'ai disclosure'),
    (r'\bdisclose ai\b', 'disclose ai'),
    (r'\bai transparency\b', 'ai transparency'),
    (r'\bai guidelines\b', 'ai guidelines'),
    (r'\bai rules\b', 'ai rules'),
    (r'\bpolicy on ai\b', 'policy on ai'),
    (r'\bpolicies.*\bai\b', 'policies...ai'),
    (r'\bai.*\bpolicy\b', 'ai...policy'),
    (r'\bai (?:is |are )?(?:not )?(?:allowed|permitted|welcome|accepted|prohibited|forbidden|banned|discouraged|encouraged|supported)\b', 'ai [not] [stance]'),
    (r'\b(?:allow|permit|welcome|accept|prohibit|forbid|ban|discourage|encourage|support).*\bai\b', '[stance_verb]...ai'),
    (r'\bno ai\b', 'no ai'),
    (r'\bai[- ]?free\b', 'ai-free'),
    (r'\bdisclose.*(?:ai|artificial)\b', 'disclose...ai'),
    (r'\b(?:ai|artificial).*disclose\b', 'ai...disclose'),
    (r'\bmark.*\bai[- ]?generated\b', 'mark ai-generated'),
    (r'\blabel.*\bai[- ]?generated\b', 'label ai-generated'),
    (r'\btag.*\bai[- ]?generated\b', 'tag ai-generated'),
    (r'\bflag.*\bai[- ]?generated\b', 'flag ai-generated'),
    (r'\b(?:ai|artificial).*(?:attribution|credit|acknowledge)\b', 'ai...attribution'),
    (r'\b(?:attribution|credit|acknowledge).*\bai\b', 'attribution...ai'),
    (r'\bresponsible for ai\b', 'responsible for ai'),
    (r'\bai.*\bresponsib\b', 'ai...responsible'),
    (r'\bresponsib.*\bai\b', 'responsible...ai'),
    (r'\bai.*\baccountab\b', 'ai...accountable'),
    (r'\baccountab.*\bai\b', 'accountable...ai'),
    (r'\bhuman.*\breview.*\bai\b', 'human...review...ai'),
    (r'\bai.*\breview.*\bhuman\b', 'ai...review...human'),
    (r'\bunderstand.*\bai[- ]?generated\b', 'understand ai-generated'),
    (r'\bai[- ]?generated.*\bunderstand\b', 'ai-generated...understand'),
    (r'\bai[- ]?assisted (?:contribut|develop|cod|work)\b', 'ai-assisted [activity]'),
    (r'\bai[- ]?assistance (?:policy|guideline|rule|statement)\b', 'ai-assistance [policy_type]'),
    (r'\b(?:contribution|contributions|contributing).*\bai\b', 'contribution...ai'),
    (r'\bhuman (?:oversight|review|approval|verification)\b.*\bai\b', 'human [oversight]...ai'),
    (r'\bai\b.*\bhuman (?:oversight|review|approval|verification)\b', 'ai...human [oversight]'),
    (r'\breview.*\bai[- ]?generated\b', 'review ai-generated'),
    (r'\bai (?:declaration|statement|disclaimer|notice)\b', 'ai [declaration_type]'),
    (r'\bdeclaration.*\bai\b', 'declaration...ai'),
    (r'\bstatement.*\bai\b', 'statement...ai'),
    (r'\bstance on ai\b', 'stance on ai'),
    (r'\bposition on ai\b', 'position on ai'),
    (r'\bapproach to ai\b', 'approach to ai'),
    (r'\bartificial intelligence.*(?:policy|guideline|rule|statement)\b', 'artificial intelligence...policy'),
    (r'\b(?:policy|guideline|rule|statement).*artificial intelligence\b', 'policy...artificial intelligence'),
    # Additional L3 patterns (prohibition/stance nouns)
    (r'\bno (?:llm|ai|large language|generative)\b', 'no [AI/LLM]'),
    (r'\bdo not (?:use|accept|allow|permit|submit) (?:ai|llm|gpt|chatgpt|copilot|claude)\b', 'do not [verb] [AI/LLM]'),
    (r'\b(?:must|should|are expected) (?:not |to not |)(?:use|rely on|submit|contribute) (?:ai|llm|gpt)\b', 'must/should not [use] AI'),
    (r'\b(?:ban|block|reject|refuse|disallow)\b.*\b(?:ai|llm|gpt|copilot|chatgpt|claude)\b', 'ban/reject AI'),
    (r'\b(?:ai|llm|gpt|copilot)\b.*\b(?:ban|block|reject|refuse|disallow)\b', 'AI ban/reject'),
    (r'\b(?:ai|llm)\b.*\b(?:not allowed|not accepted|not permitted|not welcome|not welcome)\b', 'AI not allowed'),
    (r"\b(?:not|don'?t|do not|should not|must not)\s+(?:use|rely on|submit|accept|contribute|include|rely)\s+(?:ai|llm|gpt|copilot|chatgpt|claude)\b", 'not use/rely AI'),
    (r'\b(?:ai|llm)\s+(?:output|code|content|contribution|generated)\b', 'AI [noun]'),
    (r'\b(?:contribut|submitt|pull request|pr|commit|code)\b.*\b(?:ai|llm|gpt|copilot|chatgpt)\b', 'contribution...AI tool'),
    (r'\b(?:ai|llm)\b.*\b(?:contribut|submitt|review|human|manual|hand)\b', 'AI...contribution/human'),
    (r'\b(?:ai|llm|machine|automated)\b.*\b(?:policy|guideline|rule|statement|section)\b', 'AI/LLM policy/guideline'),
    (r'\b(?:policy|guideline|rule|statement|section)\b.*\b(?:ai|llm|machine|automated)\b', 'policy/guideline...AI/LLM'),
    # More L3 patterns for common AIP phrasing
    (r'\bai[- ]?generated\s+(?:code|content|output|text|image)\b', 'ai-generated [content type]'),
    (r'\b(?:code|content|output|text|image)\s+generated\s+by\s+(?:ai|artificial)\b', '[content] generated by AI'),
    (r'\bartificial\s+intelligence\b', 'artificial intelligence'),
    (r'\b(?:welcome|accept|allow|encourage|support|permit)\s+(?:ai|llm)\b', 'welcome/allow AI'),
    (r'\b(?:welcome|accept|allow|encourage|support|permit)\b.*\bai[- ]?(?:assisted|generated)\b', 'welcome AI-assisted/generated'),
    (r'\bai[- ]?(?:assisted|generated)\b.*\b(?:welcome|accept|allow|encourage|support|permit|required|must|should)\b', 'AI-assisted/generated...welcome/require'),
    (r'\b(?:must|should|need|required|expected)\b.*\b(?:ai|llm)\b', 'must/should...AI'),
    (r'\b(?:ai|llm)\b.*\b(?:must|should|need|required|expected)\b', 'AI...must/should'),
    (r'\b(?:review|verify|check|approve|validate)\b.*\bai[- ]?generated\b', 'review/verify AI-generated'),
    (r'\bai[- ]?generated\b.*\b(?:review|verify|check|approve|validate)\b', 'AI-generated...review/verify'),
    (r'\b(?:rights?|right|licen[cs]e|ownership|intellectual property)\b.*\bai\b', 'rights/license...AI'),
    (r'\bai\b.*\b(?:rights?|right|licen[cs]e|ownership|intellectual property)\b', 'AI...rights/license'),
]

# Pre-compile patterns
COMPILED_L2 = [(re.compile(p, re.IGNORECASE), label) for p, label in L2_PATTERNS]
COMPILED_L3 = [(re.compile(p, re.IGNORECASE), label) for p, label in L3_PATTERNS]


def check_commit_for_aip(content):
    """Check if content matches at least one L2 AND at least one L3 pattern.
    Returns (has_l2, has_l3, l2_labels, l3_labels)."""
    if not content:
        return False, False, [], []
    
    l2_labels = []
    l3_labels = []
    
    for pat, label in COMPILED_L2:
        if pat.search(content):
            l2_labels.append(label)
    
    for pat, label in COMPILED_L3:
        if pat.search(content):
            l3_labels.append(label)
    
    has_l2 = len(l2_labels) > 0
    has_l3 = len(l3_labels) > 0
    
    return has_l2, has_l3, l2_labels, l3_labels


def main():
    db = pymysql.connect(host=DB_HOST, port=DB_PORT, user=DB_USER, password=DB_PASS, database=DB_NAME, charset='utf8mb4')
    cur = db.cursor()
    
    # Get all repos with human_label='Y' and AIP content
    cur.execute("""
        SELECT repo_name, ai_policy_first_date, ai_policy_content 
        FROM repos_select 
        WHERE ai_policy_human_label='Y'
    """)
    repos = cur.fetchall()
    print(f"Total repos with human_label='Y': {len(repos)}")
    
    results = []
    no_history = 0
    no_match = 0
    updated = 0
    same_as_original = 0
    different_from_original = 0
    
    for i, (repo_name, original_date, ai_content) in enumerate(repos):
        if (i + 1) % 100 == 0:
            print(f"  [{i+1}/{len(repos)}] Updated: {updated}, No match: {no_match}, No history: {no_history}")
        
        # Get all commits for this repo, ordered by commit_date ASC
        cur.execute("""
            SELECT commit_sha, commit_date, file_local_path, file_path 
            FROM contributing_md_history 
            WHERE repo_name = %s 
            ORDER BY commit_date ASC
        """, (repo_name,))
        rows = cur.fetchall()
        
        if not rows:
            no_history += 1
            results.append({
                'repo_name': repo_name,
                'original_first_date': str(original_date) if original_date else '',
                'keyword_first_date': '',
                'first_l2_labels': '',
                'first_l3_labels': '',
                'total_commits': 0,
                'match_status': 'no_history'
            })
            continue
        
        first_aip_date = None
        first_l2 = []
        first_l3 = []
        
        for sha, commit_date, local_path, file_path in rows:
            if not local_path or not os.path.exists(local_path):
                continue
            
            try:
                with open(local_path, 'r', encoding='utf-8', errors='replace') as f:
                    content = f.read()
            except Exception:
                continue
            
            has_l2, has_l3, l2_labels, l3_labels = check_commit_for_aip(content)
            
            if has_l2 and has_l3:
                first_aip_date = commit_date
                first_l2 = l2_labels
                first_l3 = l3_labels
                break
        
        if first_aip_date:
            # Compare with original
            orig_str = str(original_date)[:10] if original_date else ''
            new_str = str(first_aip_date)[:10]
            is_same = (orig_str == new_str)
            
            if is_same:
                same_as_original += 1
            else:
                different_from_original += 1
                print(f"  DIFF: {repo_name}: original={orig_str} -> keyword={new_str}")
            
            results.append({
                'repo_name': repo_name,
                'original_first_date': orig_str,
                'keyword_first_date': new_str,
                'first_l2_labels': '; '.join(first_l2[:5]),
                'first_l3_labels': '; '.join(first_l3[:5]),
                'total_commits': len(rows),
                'match_status': 'same' if is_same else 'different'
            })
            updated += 1
        else:
            no_match += 1
            results.append({
                'repo_name': repo_name,
                'original_first_date': str(original_date)[:10] if original_date else '',
                'keyword_first_date': '',
                'first_l2_labels': '',
                'first_l3_labels': '',
                'total_commits': len(rows),
                'match_status': 'no_keyword_match'
            })
    
    print(f"\n=== Summary ===")
    print(f"Total repos: {len(repos)}")
    print(f"Keyword match found: {updated}")
    print(f"Same as original: {same_as_original}")
    print(f"Different from original: {different_from_original}")
    print(f"No keyword match: {no_match}")
    print(f"No history: {no_history}")
    
    # Save results
    df = pd.DataFrame(results)
    output_path = Path('data/repos/aip_first_date_keyword_check.csv')
    df.to_csv(output_path, index=False)
    print(f"\nResults saved to {output_path}")
    
    db.close()


if __name__ == '__main__':
    main()